document.addEventListener("DOMContentLoaded", function () {

  function getNumber(id) {
      const value = document.getElementById(id).value;
      const number = parseFloat(value);
      return isNaN(number) ? 0 : number;
  }
  
  function getText(id) {
      const value = document.getElementById(id).value.trim();
      return value === "" ? "Segment" : value;
  }
  
  document.getElementById("calculateButton").addEventListener("click", function () {
  
      const segments = [];
  
      for (let i = 1; i <= 6; i++) {
  
          const name = getText("segmentName" + i);
          const revenue = getNumber("revenue" + i);
          const margin = getNumber("margin" + i);
  
          if (revenue > 0 && margin > 0) {
  
              const profit = revenue * (margin / 100);
  
              segments.push({
                  name: name,
                  revenue: revenue,
                  margin: margin,
                  profit: profit
              });
  
          }
  
      }
  
      if (segments.length === 0) {
          document.getElementById("result").innerHTML = "<p>Please enter at least one revenue segment with revenue and margin values.</p>";
          return;
      }
  
      const totalProfit = segments.reduce((sum, s) => sum + s.profit, 0);
  
      segments.sort((a, b) => b.profit - a.profit);
  
      const topSegment = segments[0];
      const secondSegment = segments[1];
  
      const topShare = (topSegment.profit / totalProfit) * 100;
      const topTwoProfit = topSegment.profit + (secondSegment ? secondSegment.profit : 0);
      const topTwoShare = (topTwoProfit / totalProfit) * 100;
  
      let interpretation = "";
      let structural = "";
      let strategic = "";
  
      if (topShare > 60) {
  
          interpretation = "A large share of total profit appears to originate from a single revenue segment. Even if other areas generate meaningful revenue, they contribute far less to the profit pool.";
  
          structural = "This structure usually indicates that the company’s economic engine is narrower than headline revenue figures suggest. Operational stability may therefore depend heavily on maintaining the performance of the leading segment.";
  
          strategic = "When profit concentration is this high, disruption in pricing, demand, or supplier conditions within that segment can disproportionately affect overall profitability.";
  
      } else if (topTwoShare > 70) {
  
          interpretation = "Most profit appears to be generated by two segments rather than being evenly distributed across the business.";
  
          structural = "This pattern is common in businesses that appear diversified operationally but are financially dependent on a small number of strong margin activities.";
  
          strategic = "Management attention typically needs to focus on protecting the economics of those segments while gradually building additional profit drivers elsewhere in the business.";
  
      } else {
  
          interpretation = "Profit appears to be distributed across multiple segments rather than dominated by a single activity.";
  
          structural = "A broader profit base often indicates that the business has several functioning economic engines rather than relying on a single dominant driver.";
  
          strategic = "Diversified profit generation generally increases resilience because operational disruption in one area is less likely to materially destabilize overall profitability.";
  
      }
  
      const metrics = `
          <h3>Calculated Metrics</h3>
          <p>Total Estimated Gross Profit: ${totalProfit.toLocaleString()}</p>
          <p>Top Segment Profit Share: ${topShare.toFixed(1)}%</p>
          <p>Top Two Segments Combined: ${topTwoShare.toFixed(1)}%</p>
      `;
  
      const output = `
          ${metrics}
  
          <h3>Interpretation</h3>
          <p>${interpretation}</p>
  
          <h3>Structural Implications</h3>
          <p>${structural}</p>
  
          <h3>Strategic Observation</h3>
          <p>${strategic}</p>
  
          <hr>
  
          <p>
          This tool evaluates only one narrow dimension of a business structure. Full diagnostic engagements examine the interaction between profit drivers, cost structure, capital deployment, cash flow timing, revenue concentration, supplier leverage, and forward scenario modelling.
          </p>
  
          <p>
          The calculator therefore acts only as a simplified preview of the analytical framework used inside those engagements.
          </p>
  
          <p>
          Because this work requires detailed modelling and careful interpretation, MJB Strategic intentionally works with a limited number of companies at any given time.
          </p>
  
          <p>
          If the thinking behind this tool resonates with how you evaluate your business, you are welcome to reach out to determine whether there may be a sensible fit to work together.
          </p>
      `;
  
      document.getElementById("result").innerHTML = output;
  
  });
  
  document.getElementById("shareWhatsAppButton").addEventListener("click", function () {
  
      const url = window.location.href;
      const shareUrl = "https://api.whatsapp.com/send?text=" + encodeURIComponent(url);
  
      window.open(shareUrl, "_blank");
  
  });
  
  });