document.addEventListener("DOMContentLoaded", function () {

    const calculateButton = document.getElementById("calculateButton");
    const resultContainer = document.getElementById("result");
    const shareButton = document.getElementById("shareWhatsAppButton");
  
    function getNumber(id) {
      const value = document.getElementById(id).value;
      const num = parseFloat(value);
      return isNaN(num) ? 0 : num;
    }
  
    calculateButton.addEventListener("click", function () {
  
      const segments = [];
  
      for (let i = 1; i <= 6; i++) {
  
        const revenue = getNumber("revenue" + i);
        const margin = getNumber("margin" + i);
  
        if (revenue > 0 && margin > 0) {
  
          const profit = revenue * (margin / 100);
  
          segments.push({
            revenue: revenue,
            margin: margin,
            profit: profit
          });
  
        }
  
      }
  
      if (segments.length === 0) {
  
        resultContainer.innerHTML = "<p>Please enter at least one revenue segment.</p>";
        return;
  
      }
  
      const totalProfit = segments.reduce(function (sum, s) {
        return sum + s.profit;
      }, 0);
  
      segments.sort(function (a, b) {
        return b.profit - a.profit;
      });
  
      const topSegmentProfit = segments[0].profit;
      const topTwoProfit = segments.slice(0, 2).reduce(function (sum, s) {
        return sum + s.profit;
      }, 0);
  
      const topShare = (topSegmentProfit / totalProfit) * 100;
      const topTwoShare = (topTwoProfit / totalProfit) * 100;
  
      let interpretation = "";
  
      if (topShare > 50) {
  
        interpretation = "A majority of total profit is generated by a single segment. This typically indicates a narrow economic engine where the financial performance of the business is heavily dependent on one dominant activity.";
  
      } else if (topTwoShare > 70) {
  
        interpretation = "Most profit appears to be generated by a small number of segments. This suggests a moderate concentration of economic value where a limited set of activities carries a large share of profitability.";
  
      } else {
  
        interpretation = "Profit generation appears relatively distributed across multiple segments. This often indicates that the business benefits from a broader base of profit drivers rather than a single dominant contributor.";
  
      }
  
      const structural = "When profit generation is concentrated, operational attention tends to focus on protecting the strongest revenue engines. Businesses with this structure may perform well while those activities remain stable, but disruptions affecting those segments can materially weaken overall profitability.";
  
      const strategic = "Operators often use this type of analysis to decide where management attention should be focused. Highly concentrated profit structures may require deliberate diversification or protective strategy around the dominant segments, while more diversified profit engines tend to create structural resilience across market cycles.";
  
      const reportHTML = `
        <h2>Diagnostic Report</h2>
  
        <h3>Calculated metrics</h3>
  
        <p>Total estimated profit: ${totalProfit.toFixed(2)}</p>
  
        <p>Profit generated by the top segment: ${topShare.toFixed(1)}%</p>
  
        <p>Profit generated by the top two segments: ${topTwoShare.toFixed(1)}%</p>
  
        <h3>Interpretation</h3>
  
        <p>${interpretation}</p>
  
        <h3>Structural implications</h3>
  
        <p>${structural}</p>
  
        <h3>Strategic observation</h3>
  
        <p>${strategic}</p>
  
        <p>
          This tool evaluates only one narrow dimension of a business structure. Full diagnostic engagements examine the interaction between profit drivers, cost structure, capital deployment, cash flow timing, revenue concentration, supplier leverage, and forward scenario modelling.
        </p>
  
        <p>
          The calculator therefore acts only as a simplified preview of the analytical framework used inside those engagements.
        </p>
  
        <p>
          Because this work requires detailed modelling and careful interpretation, MJB Strategic intentionally works with a limited number of companies at any given time.
        </p>
  
        <p>
          If the thinking behind this tool resonates with how you evaluate your business, you are welcome to reach out to determine whether there may be a sensible fit to work together.
        </p>
      `;
  
      resultContainer.innerHTML = reportHTML;
  
    });
  
    shareButton.addEventListener("click", function () {
  
      const url = encodeURIComponent(window.location.href);
      const whatsappURL = "https://api.whatsapp.com/send?text=" + url;
  
      window.open(whatsappURL, "_blank");
  
    });
  
  });