document.addEventListener("DOMContentLoaded", function () {

  const calculateButton = document.getElementById("calculateButton");
  const shareButton = document.getElementById("shareWhatsAppButton");
  const resultContainer = document.getElementById("result");

  function showError(message) {
    resultContainer.innerHTML = "<p style='color:#b91c1c;font-weight:600'>" + message + "</p>";
  }

  function runDiagnostic() {

    const segments = [];

    for (let i = 1; i <= 6; i++) {

      const revenueInput = document.getElementById("segment" + i + "Revenue");
      const marginInput = document.getElementById("segment" + i + "Margin");

      if (!revenueInput || !marginInput) {
        continue;
      }

      const revenue = parseFloat(revenueInput.value);
      const margin = parseFloat(marginInput.value);

      if (!isNaN(revenue) && !isNaN(margin)) {

        const profit = revenue * (margin / 100);

        segments.push({
          revenue: revenue,
          margin: margin,
          profit: profit
        });

      }

    }

    if (segments.length === 0) {
      showError("Please enter at least one valid revenue segment with revenue and margin.");
      return;
    }

    let totalProfit = 0;

    segments.forEach(function (segment) {
      totalProfit += segment.profit;
    });

    if (totalProfit <= 0) {
      showError("Total profit must be greater than zero for this diagnostic.");
      return;
    }

    segments.sort(function (a, b) {
      return b.profit - a.profit;
    });

    const topSegmentProfit = segments[0].profit;
    const topTwoProfit = segments.slice(0, 2).reduce(function (sum, s) {
      return sum + s.profit;
    }, 0);

    const topSegmentShare = (topSegmentProfit / totalProfit) * 100;
    const topTwoShare = (topTwoProfit / totalProfit) * 100;

    let concentrationLevel = "";

    if (topSegmentShare >= 50 || topTwoShare >= 75) {
      concentrationLevel = "high";
    } else if (topSegmentShare >= 35 || topTwoShare >= 60) {
      concentrationLevel = "moderate";
    } else {
      concentrationLevel = "low";
    }

    let summaryText = "";
    let operationalText = "";
    let riskText = "";

    if (concentrationLevel === "high") {

      summaryText =
        "The analysis indicates that a large proportion of the company’s total profit is generated by a narrow set of revenue segments. The leading segment contributes approximately " +
        topSegmentShare.toFixed(1) +
        "% of total profit, while the top two segments together contribute about " +
        topTwoShare.toFixed(1) +
        "%.";

      operationalText =
        "When profit is concentrated in a small number of activities, management attention, operational capability, and pricing discipline typically become tightly linked to those areas. The health of those specific revenue streams has an outsized influence on overall business performance.";

      riskText =
        "A narrow profit base can introduce structural risk. If the most profitable segments weaken due to pricing pressure, supplier changes, customer loss, or competitive disruption, the overall profit capacity of the business can deteriorate rapidly.";

    } else if (concentrationLevel === "moderate") {

      summaryText =
        "The analysis suggests that profit is moderately concentrated across the company’s revenue segments. The most profitable segment contributes approximately " +
        topSegmentShare.toFixed(1) +
        "% of total profit, while the top two segments contribute about " +
        topTwoShare.toFixed(1) +
        "%.";

      operationalText =
        "This structure indicates that several activities contribute meaningfully to overall profitability, although certain segments still carry greater economic weight. Operational performance in these areas will influence overall results more strongly than others.";

      riskText =
        "Moderate concentration can be manageable if management maintains visibility over the drivers of profitability in the leading segments. However, deterioration in those areas could still place pressure on margins if alternative profit sources are limited.";

    } else {

      summaryText =
        "The analysis indicates that profit is broadly distributed across the company’s revenue segments. The most profitable segment contributes approximately " +
        topSegmentShare.toFixed(1) +
        "% of total profit, while the top two segments together contribute about " +
        topTwoShare.toFixed(1) +
        "%.";

      operationalText =
        "A diversified profit structure suggests that the business generates economic value across several activities rather than relying on a single dominant segment. This distribution often provides operational resilience.";

      riskText =
        "When profit is spread across multiple segments the business is generally less exposed to disruption in any single product line, service category, or customer group. However, management must still ensure that weaker segments are not eroding margin quality.";

    }

    const report =
      "<h2>Diagnostic Summary</h2>" +
      "<p>" + summaryText + "</p>" +
      "<h2>Operational Interpretation</h2>" +
      "<p>" + operationalText + "</p>" +
      "<h2>Structural Risk Observation</h2>" +
      "<p>" + riskText + "</p>" +
      "<h2>Management Questions</h2>" +
      "<p>Which revenue segments generate the largest share of profit and what operational factors sustain their margins?</p>" +
      "<p>If the most profitable segment weakened, how quickly could other activities compensate for the lost profit contribution?</p>" +
      "<p>Are management resources aligned with the revenue segments that generate the majority of the company’s profit?</p>" +
      "<p>This calculator evaluates only one narrow dimension of business structure. The broader diagnostic work performed by MJB Strategic examines the interaction between profit drivers, cost structure, capital deployment, cash flow timing, revenue concentration, supplier dynamics, and forward operating scenarios. This type of analysis requires structured financial data and careful modelling. Only a limited number of businesses are worked with at any given time because the analysis requires detailed operational understanding. If the thinking behind this diagnostic resonates with how you view your business, you are welcome to explore whether there may be scope to work together by visiting the Contact page on the website and requesting a quote for a deeper structural diagnostic review.</p>";

    resultContainer.innerHTML = report;

  }

  calculateButton.addEventListener("click", runDiagnostic);

  shareButton.addEventListener("click", function () {

    const url = window.location.href;

    const shareLink =
      "https://api.whatsapp.com/send?text=" +
      encodeURIComponent("Useful diagnostic tool: " + url);

    window.open(shareLink, "_blank");

  });

});